@hostAddress = https://localhost:7209
@bookId = 019ec221-1775-7d29-936b-f0f127fe6e1b

POST {{hostAddress}}/api/books/
Content-Type: application/json

{
    "title": "The Pragmatic Programmer",
    "author": "Andrew Hunt",
    "isbn": "978-0201616224",
    "description": "Classic software engineering book.",
    "publishedOn": "1999-10-30",
    "pageCount": 352
}

###

GET {{hostAddress}}/api/books?pageNumber=1&pageSize=10
Accept: application/json

###

GET {{hostAddress}}/api/books/{{bookId}}
Accept: application/json

###

PUT {{hostAddress}}/api/books/{{bookId}}
Content-Type: application/json

{
    "title": "The Pragmatic Programmer (20th Anniversary Edition)",
    "author": "Andrew Hunt",
    "isbn": "978-0135957059",
    "description": "Updated edition.",
    "publishedOn": "2019-09-13",
    "pageCount": 352
}

###

DELETE {{hostAddress}}/api/books/{{bookId}}
